name: Release
on:
  push:
    branches:
      - main
      - testing
jobs:
  release:
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      TESTING: "${{ secrets.TESTING }}"
      TESTINGONE: ${{ secrets.TESTING }}
      TESTINGTWO: $TESTING
      TESTINGTHREE: ${secrets.TESTING}
      HI: HIE
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - run: echo "-$TESTING" && echo "ONE-$TESTINGONE" && echo "TWO-$TESTINGTWO" && echo "THREE-$TESTINGTHREE" && echo $HI
        
